### ISSUE TITLE
TXADMIN BOT PERMISSIONS

### ISSUE THREAD

**Issue by Kalietoo** [citizenfx/txAdmin#1002]
Hello,

I wanted to bring to your attention an issue I’m encountering when adding my bot. When I integrate the bot, I notice that the permission **"ViewCreatorMonetizationAnalytics"** is automatically included under "Integrations," even though no roles have been assigned any permissions.

When I add the bot, I make sure to uncheck all permissions, yet this specific permission remains selected and is blocking my bot's functionality.

Could you please assist me in resolving this issue?

Thank you!

**Comment by tabarra** [comment]
Since txAdmin does not initiate the bot addition process, it's 100% up to you to select the permissions.  
The bot does not require _any_ permission other than to send message in the status channel, and even that is optional.  
So if you create a bot without selecting any permission, the bot will have the same permission ad the `@everyone` role.
