### ISSUE TITLE
Live Console tab memory exhaustion

### ISSUE THREAD

**Issue by dkden7e** [citizenfx/txAdmin#153]
At least for me and with Chrome v83, Live Console is making the tabs get slow and hang after being open for a while (at least on a highly populated server).

**Comment by NoobKeksTV** [comment]
no issues for me there. u sure ur pc is fine? and u dont have to much addons installed?

**Comment by tabarra** [comment]
Added a bug-ish tag to the thread for tracking purposes.  
The issue is that we do not limit how much we put on the page.  
This will be solved in a future release, for now I recommend you adding some chrome extension to auto reload a tab every 15 minutes or so, there are many that can do that.  
  
Also, if you have this problem a lot, I recommend trying Opera, Vivaldi, or any other browser at all...
