### ISSUE TITLE
Glyphs seem kind of broken for me

### ISSUE THREAD

**Issue by bensaine** [citizenfx/txAdmin#178]
![image](https://user-images.githubusercontent.com/34781348/88705881-23ca5080-d0de-11ea-9a33-f7f1e94e8c2a.png)

I just freshly installed txadmin locally to do some testing and the menu glyph seemed kind of broken, when clicking between menu items, they sometimes fix themselves however.

**Comment by PLOKMJNB** [comment]
There seems to be no explanation for this other than something to do with when fxserver added some new http rate limits

**Comment by NoobKeksTV** [comment]
i never experienced this bug. running latest Tx & artifact 2780

But im using a Proxy so i dont have to type the IP.

**Comment by tabarra** [comment]
I have no idea what is happening!  
- This is not networking since all the SVGs come from only one file.
- I did not touch anything (not even unrelated) and this started happening.
- Although this started to being reported soon after FiveM added a new rate limiter, this happens even if connecting directly instead of the `users.cfx.url`.
- Even if this was the case, this is not networking, because some glyphs might render, others not.
- I've seen a screenshot where the icons render partially... wtf?!
- Why this never happens to me?!

weird shit right there....  
Gonna wait for some more info to come up, if anybody can find a way to reproduce that would be great.

**Comment by bensaine** [comment]
A possible common denominator would be the fact that its localhost. This is the only thing that is particular about my installation. Maybe if you try on a localhost installation you would be able to reproduce?

**Comment by jooaooalmeida** [comment]
> A possible common denominator would be the fact that its localhost. This is the only thing that is particular about my installation. Maybe if you try on a localhost installation you would be able to reproduce?

I tried it on localhost, public ip, cfx URL, for like 2 days and I still wasn't able to reproduce the issue which is the weird part, maybe it's because I'm running release instead of fxserver

**Comment by Trsak** [comment]
Seems like it really was some kind of issues with fxServer htpp rate limitings. I had this issue every time on our server, after moving to newest bulilds (2836) it never happens. 

So I would say It's fixed.

**Comment by tabarra** [comment]
That's good to hear.
