### ISSUE TITLE
txAdmin update

### ISSUE THREAD

**Issue by lukaskabc** [citizenfx/txAdmin#181]
Hello,
txAdmin was awesome resource.
I for a while not update it and today after update of FX server, when I want to update txAdmin, I noticed, that txAdmin was integrated to Fx server it self...
Well I successfuly started txAdmin and it seems working via classic server IP.
Option for SSL setup was dropped (thats not good), so you created some odd way how to secure it with reverse proxy by cfx.re (I not really like it) - and here is problem, if I start txAdmin and access the secure (https) link by cfx.re there is blank page...

Other problem is, that after switching server on, then consol start spamming 
[txAdminClient] LUA awaiting for environment setup...

Can anyone please help how to fix this problems? 

Thank you for your answer and sorry for my bad english :/

**Comment by tabarra** [comment]
Issues with the cfx.re proxy you should talk to FiveM, really doesn't depend on me.  
The direct HTTPS option was dropped due to the complexity of integrating it after refactoring and integrating with the cfx.re proxy.  
  
If you come from txAdmin v1, you need to go to your resources folder and delete the txAdminClient resource, as well as remove "start txAdminClient" from your server.cfg  
  
I'm closing this issue, if you need anything else, come to our discord server (link in the readme file)
