### ISSUE TITLE
suggestion on txAdmin - some Ideas I wanted to share.. 

### ISSUE THREAD

**Issue by Valkyrionas** [citizenfx/txAdmin#209]
Hey there, I just wanted to leave a big thank you for bringing this awesome monitoring and administration tool to the masses... I recently joined your discord and there were no places to leave a suggestion so I just wanted to leave an idea here, the tool till now works great with artifacts 2967 but I would love some more options... 

1.) the option to give a choosed username to display at the broadcasts as the default linked fivem-accountname (yea I missed to give me a nickname there... and noboday has to know my realname if I warn/kick/ban users for a reason.
2.) an option to give about 5-10 spaces of brackets where we can just type in some messages which will be displayed on a planned time, as example: " [Announcement] : Server restarts every day at 05am and 05pm" @ every hour or configured (15,30,60mins) 
3.) an option to give the (broadcast) a title to rename it and maybe to set a coloration to it ? 
as examble  "^1(Broadcast): This announcement should seem to be red)" or
"^2(News): this message should be  green accordingly to the rest of the colouration-theme like its on the servernames, and the title changed from broadcast to news, you sea? "

would really aprecciate it if there are any plans maybe to implement it in the existing code... but again, the tool already here is great and awesome work till here !  stay healthy on these times.. :) thank you!

**Comment by tabarra** [comment]
Hey @Valkyrionas, thanks for the suggestions.  
1. The username is arbitrary, except for the master account.... unfortunately this seems more like an edge case.  
2. Could be done, but honestly there are plenty of scripts already to do that... doing this in txAdmin wouldn't add much value to it.
3. Should be easy to modify this yourself. I generally don't give the users the option to change this because everybody would remove the "txAdmin" name... and since we don't even have a forum thread, this is basically the only way people hear about this project (hence the reason why it grows very slow).

Hope my answers were somewhat satisfactory.
