### ISSUE TITLE
option to disable partial crash detection since my server is pure shit and I like the smell

### ISSUE THREAD

**Issue by FROST-D** [citizenfx/txAdmin#219]
Just as the title say the partial crash detection is really bad written and it cause often problem  with random unnecessary server restart

**Comment by NonStopGamer** [comment]
I believe you mean your server is badly written

**Comment by PLOKMJNB** [comment]
This is not a txAdmin issue, this is an issue with your server. Don't go blaming txAdmin for telling you something wrong is happening.

**Comment by tabarra** [comment]
Didn't post your txAdmin version.  
Didn't post a screenshot of the diagnostics page.  
Didn't post a good description of what is happening.
Didn't post a screenshot of the terminal with the crash message.  
Didn't post a screenshot of the txAdmin log.  
  
Okay buddy retard, sure you know better than a system used by thousands and battle-tested for over a year that has 3 REDUNDANT system that checks your server literally 144 THOUSAND times a day.  
Since its badly written, please do make a PR or just shut the fuck up.

**Comment by FROST-D** [comment]
man i have other things to do that review code of a webpanel that fivem just thought to built in their system.
Anyway i am quite sure that in older version that option was there, and talking about bad written server just tell me why a "well" written server need a "crash detection".
I don't know exactly what cause the problem, we got plenty of ddos attacks recently all througths txadmin port and i don't kwno how they managed to prevent the HB, that cause and unwanted restart.
Removed txadmin and no more random restart.
I told you all i have to say, do as you want if i could i will try to recover more informations\logs etc as soon as possible
this is the image sent me from server "helpers", unfortunately i wasn't connected when this happened

![TX_HB](https://user-images.githubusercontent.com/8178000/96174722-feedb880-0f29-11eb-93f5-8ff05ddf11e3.PNG)

**Comment by jooaooalmeida** [comment]
> man i have other things to do that review code of a webpanel that fivem just thought to built in their system.

 Well, u had the time to create a PR in a Open Source platform literally saying "Its bad written like i say in the title"

> Anyway i am quite sure that in older version that option was there, and talking about bad written server just tell me why a "well" written server need a "crash detection".

 It wasn't, and the crash detection is there because txAdmin isnt only focused in well developed servers, its for everyone, plus if 
 your server gets attacked while ur asleep txadmin brings it back

> Removed txadmin and no more random restart.

 Well ofc, txadmin is handling the restart, not FXServer, txadmin is the MONITOR like the resource name says

> I told you all i have to say

Without a fundament yes



ps: join discord if u want support
