### ISSUE TITLE
Whitelist import ?

### ISSUE THREAD

**Issue by rdlh** [citizenfx/txAdmin#241]
Hi there !

- Is there a way to import a whitelist (`steam:...`) into txAdmin ? We'd love to drop our legacy WL script to enable txAdmin one.
- Is there a way to disable WL requests and to allow only admins to add / remove whitelisted users ?

Thanks and congrats on the great job!

**Comment by PLOKMJNB** [comment]
Whitelist requests are submitted as soon as someone trys to connect to the server, with those request id's Admins use the discord channel (if properly setup) to whitelist that player (i.e. /addwl GD8D-83H3) or straight from the web interface

**Comment by tabarra** [comment]
Import from which resource?  
I'm currently finishing the ban import thing, and for now I didn't do whitelist importing thing since I don't know any well spread WL resource out there, and the fact that only 12% of txAdmin servers use whitelist (opposed to the 94.8% that use the ban list).

**Comment by rdlh** [comment]
Hi @PLOKMJNB @tabarra, We're using a "custom" script, reading a file containing all steamhex, and checking is the player is allowed to connect.

I can try to work on the import myself and to send a PR if needed, but is there some documentation about how are whitelisted identifiers stored ?

**Comment by tabarra** [comment]
That's why I asked the source of the whitelists.  
If its not widespread I rather not have it in txAdmin... I like to keep it lean (check the feature graveyard docs).  
  
Saving a whitelist is rather easy, just make sure you follow the convention and the function used to generate the action IDs (that's very fucking important!)  
For reference:
```
src\components\playerController\index.js -> registerAction
```  
  
I'm closing this issue, but feel free to continue discussing here if you feel like it is needed.
