### ISSUE TITLE
[Request] Discord bot integration to show current queue

### ISSUE THREAD

**Issue by Duckerr** [citizenfx/txAdmin#310]
The current bot has IP, Players, and uptime. It would be a great addition to be able to grab the current queue amount.

**Comment by n0tsiege** [comment]
As txAdmin does not have a queue system integrated, I'm not sure how possible this would be. However, if someone created and PRed or suggested a txAdmin queue, there's a chance it could be added.

**Comment by n0tsiege** [comment]
Now, as for a Discord bot integration with an existing queue resource, that is quite possible. I'm not shutting down your idea and I don't make the decisions, I'm offering a a suggestion of my own.

**Comment by Duckerr** [comment]
@notsiege-dev No worries, I'm trying to figure out how to implement it with Connect-Queue. There's a server convar to show queue in that resource, maybe there could be an option in txAdmin for that convar since it seems to be the most popular queue being used.

**Comment by tabarra** [comment]
The issue is that txAdmin must maintain itself framework/resource agnostic.  
If we were to make any exception, would be for some ESX features since there are basically 9 thousand servers using it - and it would still be completely optional.  
If many queue resources decides "ohh, let me export this convar with standard name" then sure, we could get that data, but I just don't see it happening soon.
