### ISSUE TITLE
[ SUGGESTION ] Add-On Recipes

### ISSUE THREAD

**Issue by Arm-0001** [citizenfx/txAdmin#324]
Hello, tabarra! I was wondering if you could add the option to run recipes after the server was already created to say install resources and what not. This could be great for people who don't know how to install some resources that require importing SQL files and what not and the maker could just give them the recipe and it would do it all automatically. Maybe add a button on the resources tab titled "add a resource" and it would give you the recipe screen

**Comment by tabarra** [comment]
Oof integrating some new workflow to the recipe engine sounds like a nightmare...  
Still an interesting idea that I actually want to do, but more likely will only be done when we get an file browser/editor.
  
I'm closing this issue though, since this is more an idea than something that I can actually do right now.
