### ISSUE TITLE
[Feature]: Save player identifier history

### ISSUE THREAD

**Issue by czsquizer** [citizenfx/txAdmin#385]
Hello,
I have a suggestion about identifiers. I think that would be cool to save all the identifiers when a player disconnects.
What would it server for:
- Banning: A lot of people have many GTA accounts (especialy hackers) and if you ban their rockstar license, they change the rockstar account and log back. If we would banned all identifiers on offline ban we find, it will be much harder to join back for the same players.
- Searching players: It would also help for easier searching players by other identifiers

I know, there is one con and that the database file may be a little bit bigger but I think that it would be definitely worth it.

Thank you in advance for reading my (this) suggestion
Have a nice day, Squizer

**Comment by Kraleemil** [comment]
yeah it would be nice to samme all there Identifiers there have steam, ip, licenes, discord, xbl and so on

**Comment by L4wlz** [comment]
Hi there.. Is there any status on this one :) could be a nice feature.. :)

**Comment by tabarra** [comment]
@L4wlz  It's in progress, but it will take at least 3 months.

**Comment by Kraleemil** [comment]
> @L4wlz  It's in progress, but it will take at least 3 months.

I am excited

**Comment by L4wlz** [comment]
@tabarra that sounds AWESOME ! :D can't wait for it.. :)

**Comment by Rentux** [comment]
Hello are there any updates?

**Comment by Kraleemil** [comment]
> Hello are there any updates?

He said 3 months for 1 month ago

**Comment by Rentux** [comment]
@Kraleemil Yes

**Comment by L4wlz** [comment]
Maybe on thing to add to this.. :) 
When people joining the server they are getting an ID
![image](https://user-images.githubusercontent.com/62191448/180035919-4351ea40-3907-46d3-b97e-0ae294bddc55.png)
Will this also be saved.. or maybe logged together with the 
**joined with identifiers [steam:  xbl: live: discord: fivem: license2:]**
So have added one more with serverid: **joined with identifiers [steam:  xbl: live: discord: fivem: license2: serverid:]**

Because in QBCore as a standard the id will change everytime people is relogging.. :) so could be awesome and also easy to remember if someone has been reported.. that they can just mention the id number and then admins can look in the logs for that specific id. :)

**Comment by tabarra** [comment]
@L4wlz I don't think we can fit that into our db schema.
But in the server logs, you can always see the server id of that person.

**Comment by L4wlz** [comment]
@tabarra what is the status on this one :)

**Comment by tabarra** [comment]
It's done and published already
