### ISSUE TITLE
Suggestion: add announcements button to Live Console

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#403]
After our most recent staff meeting with nearly a hundred staff, we determined a major issue they're having is announcements and live console. It would be ideal if we could have an "announcement" shortcut like we do for "restart" under the Live Console page. Right now most of our staff are having to rely on two tabs, one for console, one for the front page.

**Comment by tabarra** [comment]
Can you sketch what that would look like?  
Or even ask one of your devs to prepare the html+css for me, since that was a pain in the ass to get to the current state.  
  
Remember, although mobile is very uncommon, small browser screens are very much because of RDP.  
And 1120x800 seems to be a good testing resolution.  
![txadmin small screen](https://i.imgur.com/lGp54z5.png)

**Comment by chrislenga** [comment]
Sure. Let me chat with my dev team later tonight, or possibly tomorrow, and see what they say. I know we're currently backed up about a week or two, but I'll still check. Perhaps time for a second layer of buttons. :D

**Comment by TasoOneAsia** [comment]
@ChrisLenga Update?

**Comment by tabarra** [comment]
Done.
