### ISSUE TITLE
[Feature]: Add feature to see, how many bans/kicks/warns an admin issued

### ISSUE THREAD

**Issue by PC1up** [citizenfx/txAdmin#476]
### Scope

Web

### Feature Description

Add a counter to the admin manager which shows how many people each admin has banned/kicked/warned

### Use Case

You want to see how many bad ppl you have yeeted into the universe. Nah fr e.g. you wanna see how active one of your admins is and therefore want to see his bans/kicks/warns

**Comment by tabarra** [comment]
I mean, this is _kinda_ solved by v7.1, what do you think?  
When making the new admin management page (planned, not scheduled), this will be done more clearly, but Since this need has been _kinda_ solved, I might as well just close this GH issue.  
![image](https://github.com/tabarra/txAdmin/assets/1808295/cebe7067-013b-4aa3-947b-69f9b80c4f7a)
