### ISSUE TITLE
option to disable admins permissions on server logs page and also on resources and other pages

### ISSUE THREAD

**Issue by titicarabina** [citizenfx/txAdmin#481]
### Scope

Web

### Feature Description

There is a big problem that admins can see the pages where they dont have permissions . They should not be able to see the resources page , niether the server log page or master actions . They should see in the menu only the pages where you givem them acces , Why they need to know about the existance of the other pages? I think this is a big issue also with the diagnostics page for all admins because they can take crucial informations from there that can compromise your server. 

### Proposed Solution

Do not show the pages in the left menu for the pages that the admin has no permissions.

**Comment by tabarra** [comment]
> they can take crucial informations from there that can compromise your server

Like what???  
  
Let's decompose what you said:
1. Server Log page: what is secret in that page? txAdmin is for admins, and if you don't trust them to see even the chat messages, they shouldn't be admins at all.
2. Resources page: you know that the started resources list is literally public and you can see which resources ANY server is running without even joining the server, right?  
3. Diagnostics page: what is "dangerous" in that page at all? Maybe the proxy link? Nope, since admins already have the webpipe and that's fine. Maybe the OS username? Yeah tell me how that "can compromise your server".
4. Master actions: Again, what the fuck in there you think is a secret? The admins won't be able to execute any actions in there since it's limited only to the master account.  

Please, provide a single example of a "big problem" that this can cause.

**Comment by tabarra** [comment]
And let me add that in the diagnostics page, even if you have tokens in the "additional arguments", they are censored.
![image](https://user-images.githubusercontent.com/1808295/139565486-77bfa0ab-7a71-43ae-b3bf-0faa9208a9b7.png)
  
This applies for `sv_licenseKeys`, `steam_webApiKey` and `sv_tebexSecret`.  
So really, @titicarabina enlighten me what is the "big problem" there...

**Comment by tabarra** [comment]
closing due to lack of evidence or argumentation
