### ISSUE TITLE
[BUG] txAdmin random crashes (when using Cfx.re URL?)

### ISSUE THREAD

**Issue by Rhydium** [citizenfx/txAdmin#497]
**txAdmin/FXServer versions:**
txAdmin 4.8.0 with FXServer version 4947 on Ubuntu 20.04 (Linux)
  
**Describe the bug**
When trying to use the Cfx.re URL after some time txAdmin crashes with this error:
(not entirely sure if this only happens w/ cfx.re url or also with direct IP:PORT, haven't entirely tested it yet)
```
[6045]: ../../../../vendor/node/src/env-inl.h:508:void node::Environment::DecreaseWaitingRequestCounter(): Assertion `(request_waiting_) >= (0)' failed.
```

**To Reproduce**
1. Go to the Cfx.re URL that txAdmin gives you
2. Use it for some time
3. It randomly stops working giving you an HTTP 502 error and logs the error above

**Expected behavior**
Just keep working without crashing

**Comment by tabarra** [comment]
after how much time?

**Comment by stevenmodl** [comment]
For me it was after 7 minutes. I just had the dashboard open.
We are using linux if it helps.

**Comment by Rhydium** [comment]
Oops, completely lost this issue in all my notifications. I also have this after around ~5 to 10 minutes.

**Comment by tabarra** [comment]
@Rhydium @XMGamingMaster Can you confirm the issue persists even after build 5102+?

**Comment by keketiger** [comment]
I am not sure if it is the same problem. But at times the panel is no longer accessible.
(This does not happen to everybody)

![Sans titre](https://user-images.githubusercontent.com/34973659/147424495-d7aa31cf-302b-41ed-8651-35dc5df8af86.png)

**Comment by tabarra** [comment]
Due to the lack of reproducible steps (that anyone can reproduce) I'm closing this issue.  
If anyone has any new information, feel free to post it here.

**Comment by Enz0Z** [comment]
Hello! I am currently having this issue, using the public ip and port everything works as expected, but using the cfx link it crashes almost immediately. Is there anything I can help you with to try and fix the error? Maybe `.dmp` or something.

**Comment by tabarra** [comment]
@Enz0Z Yes, a dmp would help.

**Comment by Enz0Z** [comment]
There you are!
[crash.zip](https://github.com/tabarra/txAdmin/files/8189411/crash.zip)

**Comment by DevShadowTV** [comment]
I have having the same error has anyone figured it out yet?

**Comment by alexitx** [comment]
Please reopen.

The Cfx reverse proxy is unusable for me since txAdmin crashes pretty much immediately after logging in with the exact same error:
```
[929]: ../../../../vendor/node/src/env-inl.h:508:void node::Environment::DecreaseWaitingRequestCounter(): Assertion `(request_waiting_) >= (0)' failed.
```

This looks like a race condition since I can reproduce it very consistently on slower systems.
Tested on a Windows machine, Linux machine and Linux virtual machine. The crash occurs most frequently on the Linux VM where system resources are a bit more limited.

```
FXServer 5562
txAdmin v4.14.0
Node v16.9.1
Windows 10 x64 20H2 / Ubuntu Server 22.04 5.15.0-40-generic
```

Steps to reproduce in Ubuntu VM on VirtualBox:

1. Install Ubuntu Server 22.04
2. Go to Settings > System > Motherboard and set adequate memory (4/8GB should be enough)
3. Go to Settings > System > Processor and set number of processors to something low (2-4) or lower the execution cap to 25-50% to simulate slow down of the system in order to get the crash more frequently
4. Go to Settings > Network > Adapter 1 and enable NAT or bridged network adapter for internet connectivity
5. Install FXServer 5562 / txAdmin v4.14.0
6. Run the server and access txAdmin via the Cfx.re proxy URL
7. Login with a Cfx.re account and continue the initial setup
8. The crash can occur upon logging in before the setup is complete or later when you're redirected to the dashboard

I didn't manage to find any logs or crash reports containing more information about the crash, but I'll try to get a core dump or more details if I can.

#374 might be related

**Comment by tabarra** [comment]
@alexitx Thanks for the detailed report.  
I have repassed this info to the Cfx.re team.
