### ISSUE TITLE
[FEATURE] SSL Support

### ISSUE THREAD

**Issue by Shorty** [citizenfx/txAdmin#504]
**Request**
Allow txAdmin to support SSL certification on a different port as previously supported during an old beta stage.

**Additional context**

https://github.com/tabarra/txAdmin/commit/27585e299f6cadcd6392824d155ed1779f84a7da

I've searched and searched to allow TxAdmin to be viewed over HTTPS, however it seems the support for this feature was removed after being in beta for a short while.

Would there be any plans to bring this back in the future, considering how much SSL is pushed by browsers these days?

**Comment by TasoOneAsia** [comment]
> Would there be any plans to bring this back in the future, considering how much SSL is pushed by browsers these days?

At the moment, there is **not** currently any plans to bring back SSL support within txAdmin itself, as we felt the compromise in maintenance, ease-of-use, and support, wasn't worth the extra feature. 

This **doesn't** mean SSL cannot be used, rather you need to setup something like a nginx reverse proxy in front of txAdmin. A quick google search should be able to get you on your way.

**Comment by tabarra** [comment]
I recommend using caddy to set up ssl in front of your txadmin, as well as rate limiting.

**Comment by silez** [comment]
Hello,

is there any news here? I've been using txAdmin for a while now and the interface is just awesome!
However, I have now switched my server completely to SSL and boom, txAdmin can no longer be called.
I get an "ERR_SSL_PROTOCOL_ERROR" error right away.
However, the certificate is correctly installed and all websites are also running correctly.

Or is there a guide somewhere where I can change that so that txAdmin can be called up again?

Thanks for the help :)

//Edit:
Okay, I've read through this a bit more.
Apparently a native SSL feature is not supported.
I have now regulated this via direct IP call, because I definitely don't want to do without SSL and HSTS for my websites :)

**Comment by tabarra** [comment]
@silez We recognize the importance of SSL, but we also decided txAdmin is not the right place to manage it.  
We suggest you protecting it through some reverse proxy or cloudflare tunnel.

**Comment by silez** [comment]
@tabarra
Thank you for your answer. The problem is only if you have completely switched your server to SSL. Because then you automatically no longer have access to txAdmin - unless you don't automatically switch from http to https and don't use hsts.
Nevertheless, it is of course your decision, I simply assigned another native IP to my server and call txAdmin over it. in addition, the surface is protected with .htaccess. should be enough for now I guess :)

In any case, thanks again :)
