### ISSUE TITLE
[Enhancement]: More margin to in-game announcements (snackbar notifications)

### ISSUE THREAD

**Issue by mickeygeecom** [citizenfx/txAdmin#553]
### Scope

In-Game Menu

### Feature Description

Due to the lack of margin (in my opinion), the notifications overlap other UI elements

### Proposed Solution

Would be nice to see something like the double or *2.5 current margin, would be perfect.

### Additional Info

![5QIkhdA](https://user-images.githubusercontent.com/5321009/147885015-a107ceea-18a1-44be-b48e-5ff0f0008d0e.jpeg)

**Comment by ghost** [comment]
See this; [menu.md](https://github.com/tabarra/txAdmin/blob/master/docs/menu.md).

You can use Convars to align the notfi. For example `+setr txAdmin-menuAlignRight true`

**Comment by TasoOneAsia** [comment]
@neptunium-dev This doesn't solve the snackbar overlap issue he has. I'll look into adjusting this a little.

**Comment by ghost** [comment]
> @neptunium-dev This doesn't solve the snackbar overlap issue he has. I'll look into adjusting this a little.

Thanks.

**Comment by mickeygeecom** [comment]
Another thing would also be to add Z-index, maybe. As other NUI elements goes in front of the alert.

p.s. bump

**Comment by tabarra** [comment]
I just checked, and doesn't seem to be trivial to set the margin.  
That being said, those notifications are temporary (or as temporary as the related action), so no real damage being done.  
Regarding announcements, very soon you will be able to overwrite the tx notification with a custom one.  
So i guess i can close this issue as a "wontfix".  
  
Regarding z-index, that is controlled by fxserver and not txAdmin. Every resource gets its own iframe so doesn't matter what we put inside, the render order will still be of the iframes themselves.  
And since tx is the first resource to start, that makes it kinda the bottom of the stack.
