### ISSUE TITLE
[BUG] Vehicle disappears in no clip

### ISSUE THREAD

**Issue by m3ftwz** [citizenfx/txAdmin#557]
**txAdmin/FXServer versions:**
v4.11.0 atop FXServer 5181
  
**Describe the bug**
Vehicles disappear if you noclip while inside of it

**To Reproduce**
1. Spawn a vehicle and get inside
2. Toggle noclip on
3. Go around for some seconds (go far away from the place you toggled noclip)
4. Toggle noclip off
5. Vehicle disappeared and is buggy somewhere in the map (sometimes i can find it looking around)

**Expected behavior**
Vehicle not to disappear

**Comment by douth-c-archive** [comment]
The vehicle reappears back onto your ped when coming back out of NoClip. It can also cause issues to keep the vehicle visible, because Gta pulls your viewing information from third or first person (i.e. you look to the right while driving a vehicle, NoClip thiks you are looking right and it goes extremely fast).

**Comment by tabarra** [comment]
Bug confirmed.  
Appears only to happen when you move somewhat far from where the noclip originally happened.  
@GoatG33k Can you maybe help us solve this?

**Comment by tabarra** [comment]
I think this one is unfixable, unfortunately :(
