### ISSUE TITLE
[Feature] Preset ban reasons/times

### ISSUE THREAD

**Issue by chrislenga** [citizenfx/txAdmin#588]
### Scope

Web

### Feature Description

Bad words filter to prevent admins from putting TOS words in when banning or kicking an entire server. 

### Use Case

Admin kicks or bans a user or the whole server.
Admin puts in TOS words that show up on players screen.

### Proposed Solution

Set up preset reasons that admins cannot change or modify for admin actions.

### Additional Info

We recently had an admin go rogue by kicking an entire server full of 128 players multiple times using the kick all function with the F-Slur. Thanks to this situation, we now have completely disabled txAdmin on this server and a huge chunk of the community now won't play the server. Few of the streamers even got suspended due to the incident causing major backlash against us. Perhaps separating kick all from kick would be wise, and something I've suggested months ago.

**Comment by douth-c-archive** [comment]
Look, we understand your frustration- but, we also fail to comprehend how a "bad word" filter would be beneficial to... literally anyone. If you, the server 'manager'/'owner', hire someone on as an admin, it's not to fall back on us (txAdmin) if they abuse or misuse given powers that YOU happen to have gave them. I personally suggest you revise who is on your staff team and the permissions they are granted. We're not responsible for stopping admin abuse, yet we do try to prevent it.

Side note: why did you 'completely disable txAdmin on your server'? That makes no sense when it was only just one administrator throwing a sissy fit.

Douth

**Comment by tabarra** [comment]
**Bad word filter:**  
Although I can totally see a feature that warns the admin that he is typing some bad word, and even an option (settings page) to block it, this won't be done because:  
- Edge case, nobody ever reported an issue like this;
- Making it warn instead of just blocking would be problematic for the menu if we consider that the list MUST support a custom word list;
- It would need to support a custom word list, since english is not the only language spoken among admins;
- I couldn't find any clear "Twitch ToS words" list, and all the "bad words" list I found online were problematic for one reason or another;
- For the reasons discussed above, it's clearly not worth the effort.

**Kick vs Kick All permission:**
This has been discussed many times, and every time the conclusion is the same: this doesn't protect anything except for some gross misclick.  
Can't kick all? Easy, just stop the server with the reason you want.  
Can't stop the server? Well if this is a twitch issue the malicious admin doesn't need to kick all, just the streamer.  
  
**Preset bans:**  
Now, _this_ is an interesting idea that I really like.  
It's not particularly feasible to make it in the current settings page but I think we can leave this one as a TODO.

**Comment by chrislenga** [comment]
> Look, we understand your frustration- but, we also fail to comprehend how a "bad word" filter would be beneficial to... literally anyone. If you, the server 'manager'/'owner', hire someone on as an admin, it's not to fall back on us (txAdmin) if they abuse or misuse given powers that YOU happen to have gave them. I personally suggest you revise who is on your staff team and the permissions they are granted. We're not responsible for stopping admin abuse, yet we do try to prevent it.
> 
> Side note: why did you 'completely disable txAdmin on your server'? That makes no sense when it was only just one administrator throwing a sissy fit.
> 
> Douth

So we actually disabled this feature as we've had a few people in the past use the kick all as a handy way to empty out the server. It makes perfect sense why we would disable txAdmin entirely and go with something that is a bit more controlled for liability reasons. Thanks for the response. I'll go ahead and close this out. 

I do wish you the best of luck. I'll close this out.

**Comment by tabarra** [comment]
\*ignores the actual response*

**Comment by douth-c-archive** [comment]
...
