### ISSUE TITLE
[Feature]: More Permissions

### ISSUE THREAD

**Issue by ghost** [citizenfx/txAdmin#624]
### Scope

Web

### Feature Description

More Permissions, for view Server Log, or resources, or Diagnostics.

### Use Case

I just want that my Supporters and mods only can ban and kick, and dont view the Server Logs or anything else, we have Discord-Logs and they should use it and not txadmin's.

### Additional Info

Would be nice if that Feature comes... :)

**Comment by tabarra** [comment]
Could you defend why you wouldn't want an server admin to see those pages?

**Comment by ghost** [comment]
> Could you defend why you wouldn't want an server admin to see those pages?

Yeah, in my logs there are things they dont need to see, and as i mentioned.. we have discord logs
and also they dont need to see the resources, or diagnostics..

**Comment by tabarra** [comment]
Due to the lack of a strong defense (really didn't reply my question), I'm closing this feature request.

**Comment by ghost** [comment]
ok xd

**Comment by PoorLatency** [comment]
> Due to the lack of a strong defense (really didn't reply my question), I'm closing this feature request.

Sorry to re-open this issue, but I highly agree with what was said here by Proxy. Not to say that we're using the same system as Proxy. The point of the permission system is to grant people elevated access to access those pages. What's the point in the permission system if people can access those tabs regardless of the permissions set? That's like you have a forum, and every person having access to the admin panel when they're just a moderator. Defeats the purpose of having a permission system when you can access any page regardless of permissions set.

Respectfully, I would think it would be best if you don't have access to view those pages, then you shouldn't see them on your tabs. Isn't that the whole purpose of setting peoples permission? For an example if someone doesn't have access to `Console` then they shouldn't see the option in the sidebar or if they click it they should get an error page.

**Comment by tabarra** [comment]
@PoorLatency _Respectfully_, your comment didn't add a single thing to the conversation.  
Everything added on a product costs time (and $) to build, it ads more code to be maintained, and adds complexity to the user.  
Because of that, we need a reason for everything to exist.  
  
Yet when I asked for a defense of this request, and didn't get any solid reason except "i don't want them to see it".  
Friendly reminder that tx**Admin** is an admin management tool. If you don't trust your admins to know who killed whom, or how much RAM the server is consuming, or the resources on your server... then txAdmin's lack of those permissions is just not gonna solve your problem.  
  
Yet² I am open to discussion and to be exposed to point of views that I do not share, sadly this GH thread couldn't provide one, hence why it was closed and I'll keep closed.
