### ISSUE TITLE
[BUG] NoClip and Ingame Menu activates after tabbing back into the game

### ISSUE THREAD

**Issue by xImChenix** [citizenfx/txAdmin#635]
**txAdmin/FXServer versions:**

v4.14.1 / 5593/ZAP
  
**Describe the bug**

If I have the permissions to open the tx-Menu, and also have the permissions to use Noclip, every time I tab into the Game (doesn't matter if with ALT + TAB, WIN. + TAB or just go on the FiveM Icon, the Noclip is activating and the tx-Menu opens. I have also deleted all keybinds for noclips etc., doesn't fix the problem.

**To Reproduce**

1. Go out of the Game
2. Go back into it
3. Noclip is active or inactive when it was active
4. tx-admin menu is open, when it was already open it closes

**Expected behavior**

Just go into the game without toggling the noclip or the tx-menu

**Additional context**
What is also very weird: If I want to set a new hotkey for any of the Tx-Admin Functions, every time I press enter to start the recognition of the keys, the function is happening, for example: if i want to set a hotkey for toggling the player IDs, when i press enter it just toggles the Player-ID Display and I can't set a hotkey.
This also happens on other Servers for example my localhost. Others doesn't seem to have this error.

I would be really happy if we find a solution for that, it is really annoying.

**Comment by tabarra** [comment]
Could not reproduce the issue.  
Maybe it's something on your pc? Keyboard layout?!  
Nobody ever reported this.  
  
Try restarting your pc and see if it still has the same issue.

**Comment by xImChenix** [comment]
I don't know why but it seems to have fixed itself. Still thanks!

**Comment by AlonHor** [comment]
Just wanted to mention for other people having this issue that I got it fixed by:
Pressing F8, typing `bind`, and at the very bottom I've noticed I have a few txAdmin commands binded to some sort of joystick that I didn't have, so fixed by typing `unbind` followed by the first 2 parameters in the last few lines that were both full capital letters, and it seemed to have fixed the issue instantly.
Just wanted this to be noted for others that may experience this issue or similar.
