### ISSUE TITLE
[BUG] restart schedule issues

### ISSUE THREAD

**Issue by Bossman02** [citizenfx/txAdmin#680]
**txAdmin/FXServer versions:**
 v4.18.0 atop FXServer 5874 
  
**Describe the bug**
When you schedule a new restart via the schedule restart button, the 2 first messages to the server say the same time, and if you have scheduled a too close restart (1 min for example) the restart doesn't happen.
Also if you want to remove all the scheduled restarts from the restarter in settings page it throws an http 500 error when save the changes

**Comment by tabarra** [comment]
Let's break it down in the 3 issues:

**Q:** When you schedule a new restart via the schedule restart button, the 2 first messages to the server say the same time
Do you mind recording a video, sending screenshot or anything? I'm having a hard time understanding the issue.
  
**Q:** have scheduled a too close restart (1 min for example) the restart doesn't happen.
This is due to the precision of the scheduler function, I'll see if i can handle it and throw a message saying it's too close.  
  
**Q:** Also if you want to remove all the scheduled restarts from the restarter in settings page it throws an http 500 error when save the changes  
Thissue has been fixed, and the fix will be available on the v4.18.1 patch release.

**Comment by tabarra** [comment]
Regarding point 2, the behavior was improved in commit d98ab7c9d8d21b59e69ca94b9787f5d3d1dcaced

**Comment by Bossman02** [comment]
i'm trying to reproduce again and record it but now it doesn't happen, maybe is some when you schedule in any period in cocnrete, but what it happens is the mesage tx send saying the server will be restart in x time says the same time in the 2 first sends, if i reproduce it i will send you the video or snapshot

**Comment by tabarra** [comment]
Alright, for now I'll close this thread ok?
