### ISSUE TITLE
[BUG] Usernames don't show up properly for those connecting

### ISSUE THREAD

**Issue by PoorLatency** [citizenfx/txAdmin#713]
**txAdmin/FXServer versions:**
v5.0.0-beta5 atop FXServer 6046
  
**Describe the bug**
In the playerlist some of the player(s) name appear to be `Unknown` and the player count is 100+.

**To Reproduce**
1. Type /tx and view the list.

**Expected behavior**
Display the name.

**Screenshots**
![Error](https://i.imgur.com/dMRjPOR.png)

**Additional context**
Windows

**Comment by tabarra** [comment]
But is it like just for a few seconds or it is persistent and the name doesn't appear afterwards?  
This part of code didn't change before beta5 where i added a "if name is nil, set name to unknown", and i only did that to fix the menu crashing issue caused by players somehow without name.  
  
I have no idea what could be the issue, in my server that just didn't happen.

**Comment by tabarra** [comment]
I have found the issue and solved it.  
Will be available in the next update, which might be the full release on monday or another beta.  
Thanks for the report!
