### ISSUE TITLE
[FEATURE]: SSO integration

### ISSUE THREAD

**Issue by boostvolt** [citizenfx/txAdmin#739]
### Scope

Web

### Feature Description

I would like to have the possibility to log in to the txAdmin web interface via SSO. But this requires an OICD or SAML interface which is currently not available in txAdmin.

### Use Case

I want to use SSO (Single Sign On) via SAML or OIDC to log in to the txAdmin web interface, but I am unable to do so. 

### Proposed Solution

Integrate SAML or OIDC.

**Comment by tabarra** [comment]
On txAdmin v2 I added code for users to be able to login with any OAuth/OIDC provider, including Discord, but I never enabled it because people would have really hard time configuring stuff like redirect URL, and that would lead to some very hard to troubleshoot issues.  
So later I decided to remove that option completely, and leave only Cfx.re as a provider.  
  
If one REALLY NEEDS this feature, probably wouldn't be to hard for them to do some workaround since our admins file is just JSON.

**Comment by Tweak4141** [comment]
I would like to see SSO support return. Perhaps provide a notice that no support would be provided in regards to SSO, or  a way to add a custom provider easier would be nice. I looked through the auth code, and it seems you still have most of the oauth code in place, just hardcoded cfx.re as a provider.

**Comment by TasoOneAsia** [comment]
Was there a specific provider in mind? Also, just curious: are you running some sort of LDAP provisioning and are looking to automate access controls to tx?

**Comment by Tweak4141** [comment]
@TasoOneAsia 
> Was there a specific provider in mind? Also, just curious: are you running some sort of LDAP provisioning and are looking to automate access controls to tx?

I run my own SSO instance, with support for SAML and OpenID. I'd like to be able to use this for login. The SSO instance uses LDAP, so you are correct in that I'm looking to automate access controls to TX.

**Comment by TasoOneAsia** [comment]
I figured that was the use case here.

A reverse proxy (i.e nginx) tied to an identity provider through whatever auth protocol of your choosing (LDAP, OIDC, what have it) could likely do what you are looking for.

**Comment by Tweak4141** [comment]
> I figured that was the use case here.
> 
> A reverse proxy (i.e nginx) tied to an identity provider through whatever auth protocol of your choosing (LDAP, OIDC, what have it) could likely do what you are looking for.

Yes, I have looked into this and is what I'm currently testing, but native support in TXAdmin would be the ideal solution. An easier way to add custom providers would be nice, currently I make my own changes to txadmin and build, but it's not as nice as having built in support.

**Comment by nick-perry14** [comment]
> > I figured that was the use case here.
> > A reverse proxy (i.e nginx) tied to an identity provider through whatever auth protocol of your choosing (LDAP, OIDC, what have it) could likely do what you are looking for.
> 
> Yes, I have looked into this and is what I'm currently testing, but native support in TXAdmin would be the ideal solution. An easier way to add custom providers would be nice, currently I make my own changes to txadmin and build, but it's not as nice as having built in support.

I agree that this could be useful... Maybe place it in an advanced place where the regular user wouldn't see this but "IYKYK" you'd be able to add a provider?

**Comment by Yanom1212** [comment]
Sad that this idea is dead

**Comment by kennyrkun** [comment]
Proper SSO is definitely a must have. That it would be too difficult to configure is a little bit ridiculous. If we're competent enough to setup a FiveM server, and install and configure all the mods we want with it, we're competent enough to configure SSO. This should be supported by TxAdmin.

**Comment by yorick2002** [comment]
> Proper SSO is definitely a must have. That it would be too difficult to configure is a little bit ridiculous. If we're competent enough to setup a FiveM server, and install and configure all the mods we want with it, we're competent enough to configure SSO. This should be supported by TxAdmin.

Keyword, "if". You have probably never done any type of FiveM/txAdmin support. Most of these people are absolute idiots on their first on a computer or so

**Comment by kennyrkun** [comment]
> You have probably never done any type of FiveM/txAdmin support. Most of these people are absolute idiots on their first on a computer or so

I wouldn't be asking for an advanced feature allowing the use of a centralized user management system for me, myself, and I. I have dozens of users across a few servers that I support. I am able to manage those users and their access to all our services from one spot, except for txAdmin. My identity provider already allows users to login using their Discord accounts.

When a new developer is brought on, or one leaves, I have to manually enter txAdmin to create or delete an account. I don't have to do this for any of our other services.

Additionally, txAdmin is put behind a reverse proxy which requires authentication. This causes a double login: once for the proxy, and again for txAdmin, each using different credentials.

Refusing to add a useful feature because you feel your own users might be too stupid to figure it out is really quite hostile.
