### ISSUE TITLE
[FEATURE]: More Features like vMenu

### ISSUE THREAD

**Issue by ENC4YP7ED** [citizenfx/txAdmin#792]
### Scope

In-Game Menu

### Feature Description

Add more Features to the Ingame TxAdmin Menu like vMenu has them like :

Car Options (Like Tuning , automatic drive)
Player Options (Like Clothing , Switch Peds , Aduty)
World Options (Like Real Ingame Time , Change Weather)
Misc Features (Like a Prop Placer)

### Use Case

First Things first people stop selling those native ui menus
Second More Server performance because its buildin into txadmin
Third would be great for Testing Stuff 

### Proposed Solution

Make it work ig

**Comment by tabarra** [comment]
Thanks for the feedback.  
Although I can see the utility of these features in many servers, I think they are out of scope for txAdmin, which is a admin tool instead of a roleplay tool.  
  
I'll be the first to admit that not everything in tx is strictly administrative, like the player super jump mode as well as car spawn and boost, but at least these were super easy to do, unlike clothing and car modding tools.
