### ISSUE TITLE
[FEATURE]: Highlight new players in web console 

### ISSUE THREAD

**Issue by robert4049** [citizenfx/txAdmin#805]
### Scope

Web

### Feature Description

In the players section, highlight players with less than 1 hour of playtime.

![image](https://user-images.githubusercontent.com/68483930/233798193-cde9ba33-499b-4d25-8dbc-a8d6905dc39d.png)

### Use Case

This would allow you to see who's need and possibly hacking, along with being able to greet new players

### Proposed Solution

Add a conditional statement regarding play time and change the css class of that object to be a new player style 

### Additional Info

None

**Comment by orel56000** [comment]
If already adding such a feature, this can have much more potential. Instead of _just_ marking the line in yellow, you could have the session playtime in plain text next to the player name. and maybe even adding a sort option, to sort by id, session playtime, total playtime, etc..

I guess this^ is a better solution to your use case, also can be useful for just interesting statistics of your server's online players.


Also, instead of marking the whole line in yellow, like your screenshot shows, you could change the color the the vertical line on the left of the player, as this is already exist and seems like more sense.
![image](https://user-images.githubusercontent.com/54208288/233820241-12b0ea11-8d02-431d-bf0a-95c4962c73f0.png)

**Comment by tabarra** [comment]
This is a very good idea, but instead of highlighting it would be nice to have it be an automatic tag, integrated with this planned feature #628

**Comment by tabarra** [comment]
Closed due to its coverage in #628
