### ISSUE TITLE
[FEATURE]: Live Map

### ISSUE THREAD

**Issue by Bentix-cs** [citizenfx/txAdmin#820]
### Scope

Web

### Feature Description

A map where you can see every player and vehicle on the Server, also maybe with different types of maps. 
You should be able to interact with the players on the map.

**Comment by ggfto** [comment]
This would be really nice! I saw a server that implemented somenthing like this, here's the link: https://github.com/supernovaplus/ttmap

**Comment by Nishena** [comment]
> This would be really nice! I saw a server that implemented somenthing like this, here's the link: https://github.com/supernovaplus/ttmap

How was this implemented? On txAdmin itself or any other way? Do you know??

**Comment by tabarra** [comment]
Although this is a cool feature, and i think this feature totally makes sense for txAdmin, I have discarded the idea because:
1. It's not trivial to do;
2. Not many people ask for it (although, i guess this can change);
3. There is already one resource that does this, and I couldn't really think what we could add to that.

And because of that, i'll close this suggestion, but I'm happy to revisit this in the future if some new ideas come to mind or enough people show interest in it.
