### ISSUE TITLE
[BUG] Route timed out : /settings/save/discord

### ISSUE THREAD

**Issue by Enyo69** [citizenfx/txAdmin#826]
**txAdmin/FXServer versions:**
6.0
  
**Describe the bug**
Error used disallowed intents^7 in index^7:137

![image](https://github.com/tabarra/txAdmin/assets/50346411/019d25a7-dbcc-41e3-ad03-c1875f1bd49f)

**Comment by tabarra** [comment]
The discord API is taking too much time to reply.  
Noted, I'll add better error handling in the future.

**Comment by AF18Games** [comment]
Im having the same issue, is there away to fix this

**Comment by tabarra** [comment]
Just to update you guys, the timeout issue (almost) only happens if your bot does not have the guild members intent enabled in the discord developer portal.  
This is caused by a bug introduced in discord.js v14.10.0, which makes intent errors unhandlable.  
The issue is that we cannot roll back to other discord.js versions because now they just broke with _another_ issue... so right now i'm kinda waiting for discord.js to release a fix for it.  
  
If you feel like this issue affects you, feel free to thumbs up my post below:  
https://github.com/discordjs/discord.js/issues/9621

**Comment by tabarra** [comment]
Solved in v6.0.1, but I forgot to close the thread.

**Comment by Caprini4613** [comment]
hi so my bot is set up just as it was on the previous version of tx admin, and after updating to 7406 like prompted it no longer lets me use my bot and my server is whitelisted, it tells me the discord api took too long, but i do have guild members intent turned on for my bot. i do get on the discord bot a code-3 red box on the left side of tx admin that says the bot ws staus: idle

**Comment by Mycroft-Studios** [comment]
> hi so my bot is set up just as it was on the previous version of tx admin, and after updating to 7406 like prompted it no longer lets me use my bot and my server is whitelisted, it tells me the discord api took too long, but i do have guild members intent turned on for my bot. i do get on the discord bot a code-3 red box on the left side of tx admin that says the bot ws staus: idle

for support visit our discord at https://discord.gg/txadmin
