### ISSUE TITLE
[FEATURE]: Qbox recipe to popular recipes

### ISSUE THREAD

**Issue by Kaparrs** [citizenfx/txAdmin#861]
### Scope

Web

### Feature Description

I'd say that qbox is a fairly popular upcoming framework that could be added to the "Popular Recipes" tab. They've got a txAdminRecipe repo: 

https://github.com/Qbox-project/txAdminRecipe

**Comment by tabarra** [comment]
Thanks for the suggestion.  
I am in talks with qbox's maintainer since forever, and I'm awaiting their signal for me to have a look at adding it to the recommended templates.  
But right now it's far from being popular, not even top 1000 resource.
![image](https://github.com/tabarra/txAdmin/assets/1808295/f574c767-b298-49c8-8efc-f492d57c1a94)  
  
For now I'm closing this issue, will add it when it's ready.
