### ISSUE TITLE
[FEATURE]: Command Ban

### ISSUE THREAD

**Issue by xSKAJ** [citizenfx/txAdmin#938]
### Scope

In-Game Menu

### Feature Description

Add the command /ban identifier reason time

**Comment by tabarra** [comment]
Web, nui, api, chat command, discord command... soon you will want me to maintain an interface for smoke signals as well.  
Too much surface, I don't want to maintain it.

**Comment by tabarra** [comment]
By the way, you can literally type `/tx <id>` to open the modal, 2 more clicks and the player is banned... way more ergonomic than `/ban <identifiers>`

**Comment by AamiRobin** [comment]
Is it possible to add an export that would allow us to ban players? For example, we have some traps for players who use cheats and as soon as they trigger those events from the Lua executor, we ban them. There is no way for other players to know or trigger those events. Therefore, it would be easier to manage all the bans from one menu. Please add an export so that we can use it. Thank you.

**Comment by iSentrie** [comment]
> By the way, you can literally type `/tx <id>` to open the modal, 2 more clicks and the player is banned... way more ergonomic than `/ban <identifiers>`

that would not work for offline players, isnt?

**Comment by tabarra** [comment]
@iSentrie For offline players you need to use the web interface.
