### ISSUE TITLE
[FEATURE]: Permission for showing player distance/mode of travel

### ISSUE THREAD

**Issue by solareon** [citizenfx/txAdmin#951]
### Scope

In-Game Menu

### Feature Description

The ability to enable/disable seeing player distances/mode of travel within the player card via permissions on the in game txAdmin menu.

### Use Case

In roleplay servers seeing the distance to players is a huge power advantage and being able to disable this "un-loggable" action for those that shouldn't have it would be great.

**Comment by tabarra** [comment]
No way I'm implementing this.  
People basically have asked for every single feature of txAdmin to be disabled due to server owners not trusting their own staff.  
This doesn't make any sense for me.  
  
If anything, what you guys want is a way to do /onduty and /offduty, and that MAYBE will come some day to txAdmin... but not today
