### ISSUE TITLE
[FEATURE]: do txadmin have a plan to support http over ssl/tls?

### ISSUE THREAD

**Issue by HJDCZY** [citizenfx/txAdmin#960]
### Scope

Web

### Feature Description

I`d like to make txadmin to support https, I want to know weather the development group have the plan about it. or I will do it myself and make pull request.

### Use Case

it can increase security

**Comment by tabarra** [comment]
Fun fact, up until mid 2020 or so, txAdmin actually supported TSL, until I decided to remove it.  
At the moment I believe txAdmin (or node in general) just isn't the correct place for SSL.  
I do agree it's necessary, but people should be using proper solutions for it like cloudflare tunnels or something like that, otherwise any weak DoS can take down txAdmin.  
So I recommend you roll out your own solution.

**Comment by HJDCZY** [comment]
ok I got what you mean, and I will try to use like proxy pass reverse on apache/nginx to achieve that. thank for your reply : )
