### ISSUE TITLE
[FEATURE]: hope TX can add anti-cheating features.

### ISSUE THREAD

**Issue by xingyue0** [citizenfx/txAdmin#983]
### Scope

Web

### Feature Description

provide anti-cheat features. I think this is very useful, especially for new server owners, as cheating in games is a big headache for them. I really hope you can add this feature; it would be very helpful.

**Comment by tabarra** [comment]
Thanks for the feat request, but long time ago it was decided that anti-cheat is outside the scope for txAdmin.  
If there is _any_ anticheat feature that would be effective in txAdmin, then that should probably be added to fivem itself and not txAdmin.  
  
Since txAdmin is on ~85% of all fivem servers, anything that I add would either be incompatible with some servers, or be useless.
