### ISSUE TITLE
[REQUEST] Option to set restart warning times.

### ISSUE THREAD

**Issue by MisterMIntBoy** [citizenfx/txAdmin#99]
Add the ability to change the frequency of notifications for scheduled restarts on Discord. It's annoying to have 30,15,10,5,4,3,2,1 minute reminders. Please allow the ability to change it to what we specify.

**Comment by tabarra** [comment]
What do you want to have, instead of `30,15,10,5,4,3,2,1`?

**Comment by MisterMIntBoy** [comment]
30, 5, and then the actual restart.

**Comment by Tuwkan618** [comment]
maybe 30, 15, 5 and 1

**Comment by Joelelfstrom** [comment]
Since no update has come, I will do it myself. I will do a pull after, should be simple

**Comment by jooaooalmeida** [comment]
> Since no fix has come, I will try fix it myself. I will post here if I manage to fix it, should be simple

How do you fix something that is not a bug????????? It's made that way, it's that way, there is no user friendly way to change it, if u guys are on github I assume u know it has source code and u can do whatever u want if it's inside the license rules... If u want to make it an option u can code it and make a pull request

Also I don't see how its annoying, do you guys keep txadmin logs in #general of your server?

**Comment by Joelelfstrom** [comment]
Was easy to find, but since the files not open for me I can't edit them. Been looking in my phone so far, so will try at home later to do a manual install

https://github.com/tabarra/txAdmin/blob/master/src/components/monitor/index.js

**Comment by Joelelfstrom** [comment]
> > Since no fix has come, I will try fix it myself. I will post here if I manage to fix it, should be simple
> 
> How do you fix something that is not a bug????????? It's made that way, it's that way, there is no user friendly way to change it, if u guys are on github I assume u know it has source code and u can do whatever u want if it's inside the license rules... If u want to make it an option u can code it and make a pull request
> 
> Also I don't see how its annoying, do you guys keep txadmin logs in #general of your server? 

So we have a channel in our discord named Server-Status where it posts restarts. It spams like above-mentioned. 
Since only each client can mute the channel we can't control notifications. So everyone get a notification 10times before restart everytime, YES it's annoying. 

I will do a pull after yes

**Comment by jooaooalmeida** [comment]
> > > Since no fix has come, I will try fix it myself. I will post here if I manage to fix it, should be simple
> > 
> > How do you fix something that is not a bug????????? It's made that way, it's that way, there is no user friendly way to change it, if u guys are on github I assume u know it has source code and u can do whatever u want if it's inside the license rules... If u want to make it an option u can code it and make a pull request
> > 
> > Also I don't see how its annoying, do you guys keep txadmin logs in #general of your server? 
> 
> So we have a channel in our discord named Server-Status where it posts restarts. It spams like above-mentioned. 
> Since only each client can mute the channel we can't control notifications. So everyone get a notification 10times before restart everytime, YES it's annoying. 
> 
> I will do a pull after yes

They don't even get tagged... If it did @ everyone server restarting in 5 minutes YES it would be annoying, but it just says server restarting in 5 minutes, I'm in multiple servers with the same logic as yours have (status room) and I never got bored, specially because if the users want to see the server status they can also just do /status

Thanks for pull requesting it when done tho

**Comment by Joelelfstrom** [comment]
> > > > Since no fix has come, I will try fix it myself. I will post here if I manage to fix it, should be simple
> > > 
> > > How do you fix something that is not a bug????????? It's made that way, it's that way, there is no user friendly way to change it, if u guys are on github I assume u know it has source code and u can do whatever u want if it's inside the license rules... If u want to make it an option u can code it and make a pull request
> > > 
> > > Also I don't see how its annoying, do you guys keep txadmin logs in #general of your server? 
> > 
> > So we have a channel in our discord named Server-Status where it posts restarts. It spams like above-mentioned. 
> > Since only each client can mute the channel we can't control notifications. So everyone get a notification 10times before restart everytime, YES it's annoying. 
> > 
> > I will do a pull after yes
> 
> They don't even get tagged... If it did @ everyone server restarting in 5 minutes YES it would be annoying, but it just says server restarting in 5 minutes, I'm in multiple servers with the same logic as yours have (status room) and I never got bored, specially because if the users want to see the server status they can also just do /status
> 
> Thanks for pull requesting it when done tho 

Yea I know but they still get sound notification s for every message. Some players don't want to mute them self's for some reason ;)

**Comment by jooaooalmeida** [comment]
> > > > > Since no fix has come, I will try fix it myself. I will post here if I manage to fix it, should be simple
> > > > 
> > > > How do you fix something that is not a bug????????? It's made that way, it's that way, there is no user friendly way to change it, if u guys are on github I assume u know it has source code and u can do whatever u want if it's inside the license rules... If u want to make it an option u can code it and make a pull request
> > > > 
> > > > Also I don't see how its annoying, do you guys keep txadmin logs in #general of your server? 
> > > 
> > > So we have a channel in our discord named Server-Status where it posts restarts. It spams like above-mentioned. 
> > > Since only each client can mute the channel we can't control notifications. So everyone get a notification 10times before restart everytime, YES it's annoying. 
> > > 
> > > I will do a pull after yes
> > 
> > They don't even get tagged... If it did @ everyone server restarting in 5 minutes YES it would be annoying, but it just says server restarting in 5 minutes, I'm in multiple servers with the same logic as yours have (status room) and I never got bored, specially because if the users want to see the server status they can also just do /status
> > 
> > Thanks for pull requesting it when done tho 
> 
> Yea I know but they still get sound notification s for every message. Some players don't want to mute them self's for some reason ;)
> 

Ahaha it's fine, appreciate if u make the pull request

**Comment by tabarra** [comment]
Every decision I make regarding txAdmin comes to only two things:  
1. Do I have the time/patience/priority to do this?  
2. Will this, in any way, make the troubleshooting of txAdmin remotely more difficult?  
  
For this case, the troubleshooting is the issue.  
When someone comes asking "why ds bot no work?", this will be one more question i will have to ask, and you might think "just ask them to send a screenshot of the settings page"... Well, you are totally wrong!  
Some people literally can't even do that.  
  
I'm proud that currently, 90% of all issues can be solved with a simple one-paragraph standard bot message like `!localhost` or `!dual`. And considering I have a IRL full-time job, this is _actually_ important.  
  
That being said, I will leave this open for now because I think I can totally have a select box with a few preset options... which can totally be done but now it comes down to priorities.  
  
**edit:** feel free to PR the select box tho.

**Comment by tabarra** [comment]
Feature added on #226
